/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-02-07 05:48:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.modules;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/workspace/spring-boot/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/legacy-spring-board-d/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1576545444085L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.2.1.RELEASE.jar", Long.valueOf(1580951416387L));
    _jspx_dependants.put("jar:file:/C:/workspace/spring-boot/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/legacy-spring-board-d/WEB-INF/lib/spring-security-taglibs-5.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1572863398000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Topbar -->\r\n");
      out.write("<nav\r\n");
      out.write("\tclass=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("\t<button id=\"sidebarToggleTop\"\r\n");
      out.write("\t\tclass=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t</button>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Topbar Search -->\r\n");
      out.write("\t<form\r\n");
      out.write("\t\tclass=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("\t\t\t\taria-describedby=\"basic-addon2\">\r\n");
      out.write("\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Topbar Navbar -->\r\n");
      out.write("\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("\t\t<li class=\"nav-item dropdown no-arrow d-sm-none\"><a\r\n");
      out.write("\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\"\r\n");
      out.write("\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\taria-expanded=\"false\"> <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("\t\t</a> <!-- Dropdown - Messages -->\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\taria-labelledby=\"searchDropdown\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("\t\t\t\t\t\t\taria-describedby=\"basic-addon2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Nav Item - Alerts -->\r\n");
      out.write("\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\taria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("\t\t\t\t<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("\t\t</a> <!-- Dropdown - Alerts -->\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\taria-labelledby=\"alertsDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Alerts Center</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-circle bg-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"font-weight-bold\">A new monthly report is\r\n");
      out.write("\t\t\t\t\t\t\tready to download!</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-circle bg-success\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-donate text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
      out.write("\t\t\t\t\t\t$290.29 has been deposited into your account!\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-circle bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
      out.write("\t\t\t\t\t\tSpending Alert: We've noticed unusually high spending for your\r\n");
      out.write("\t\t\t\t\t\taccount.\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show\r\n");
      out.write("\t\t\t\t\tAll Alerts</a>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Nav Item - Messages -->\r\n");
      out.write("\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\"\r\n");
      out.write("\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\taria-expanded=\"false\"> <i class=\"fas fa-envelope fa-fw\"></i> <!-- Counter - Messages -->\r\n");
      out.write("\t\t\t\t<span class=\"badge badge-danger badge-counter\">7</span>\r\n");
      out.write("\t\t</a> <!-- Dropdown - Messages -->\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\taria-labelledby=\"messagesDropdown\">\r\n");
      out.write("\t\t\t\t<h6 class=\"dropdown-header\">Message Center</h6>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/fn_BT9fwg_E/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-truncate\">Hi there! I am wondering if you\r\n");
      out.write("\t\t\t\t\t\t\tcan help me with a problem I've been having.</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">Emily Fowler · 58m</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/AU4VPcFN4LE/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"status-indicator\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-truncate\">I have the photos that you\r\n");
      out.write("\t\t\t\t\t\t\tordered last month, how would you like them sent to you?</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">Jae Chun · 1d</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/CS2uCrpNzJY/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"status-indicator bg-warning\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-truncate\">Last month's report looks great,\r\n");
      out.write("\t\t\t\t\t\t\tI am very happy with the progress so far, keep up the good work!</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-truncate\">Am I a good boy? The reason I ask\r\n");
      out.write("\t\t\t\t\t\t\tis because someone told me that people say this to all dogs, even\r\n");
      out.write("\t\t\t\t\t\t\tif they aren't good...</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read\r\n");
      out.write("\t\t\t\t\tMore Messages</a>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Nav Item - User Information -->\r\n");
      out.write("\t\t<li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- End of Topbar -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/modules/topbar.jsp(169,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t<a href=\"/legacy-spring-board-d/resources/login.html\" id=\"login\" role=\"button\" aria-expanded=\"false\">\r\n");
        out.write("\t\t\t\t\t<span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">로그인</span>\r\n");
        out.write("\t\t\t\t</a>\r\n");
        out.write("\t            &nbsp;\r\n");
        out.write("\t            <a href=\"/legacy-spring-board-d/resources/register.html\" id=\"join\" role=\"button\" aria-expanded=\"false\">\r\n");
        out.write("\t            \t<span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">회원가입</span>\r\n");
        out.write("\t\t\t\t</a>\r\n");
        out.write("\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/modules/topbar.jsp(178,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> \r\n");
        out.write("\t\t\t\t\t<span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">\r\n");
        out.write("\t\t\t\t\t\t");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ auth.member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("\t\t\t\t\t</span>\r\n");
        out.write("\t\t\t\t\t<img class=\"img-profile rounded-circle\" src=\"https://source.unsplash.com/QAB-WJcbgJk/60x60\">\r\n");
        out.write("\t\t\t\t</a>\r\n");
        out.write("\t\t\t\t<!-- Dropdown - User Information -->\r\n");
        out.write("\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"userDropdown\">\r\n");
        out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
        out.write("\t\t\t\t\t\t<i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t\t\t\t\tProfile\r\n");
        out.write("\t\t\t\t\t</a>\r\n");
        out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
        out.write("\t\t\t\t\t\t<i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t\t\t\t\tSettings\r\n");
        out.write("\t\t\t\t\t</a>\r\n");
        out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
        out.write("\t\t\t\t\t\t<i class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t\t\t\t\tActivity Log\r\n");
        out.write("\t\t\t\t\t</a>\r\n");
        out.write("\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
        out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"/legacy-spring-board-d/logout\">\r\n");
        out.write("\t\t\t\t\t\t<i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t\t\t\t\tLogout\r\n");
        out.write("\t\t\t\t\t</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/modules/topbar.jsp(183,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("auth");
      // /WEB-INF/views/modules/topbar.jsp(183,6) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }
}
