/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-02-05 02:11:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/workspace/spring-boot/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/08.spring-board-b/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/modules/common-js.jsp", Long.valueOf(1578373091245L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1576545444085L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("  <title>SB Admin 2 - Dashboard</title>\n");
      out.write("\n");
      out.write("  <!-- Custom fonts for this template-->\n");
      out.write("  <link href=\"/spring-board-b/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template-->\n");
      out.write("  <link href=\"/spring-board-b/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"page-top\">\n");
      out.write("\n");
      out.write("  <!-- Page Wrapper -->\n");
      out.write("  <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Content Wrapper -->\n");
      out.write("    <div id=\"content-wrapper\" class=\"d-flex flex-column\">\n");
      out.write("\n");
      out.write("      <!-- Main Content -->\n");
      out.write("      <div id=\"content\">\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/topbar.jsp", out, false);
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- Begin Page Content -->\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("          <!-- Page Heading -->\n");
      out.write("          <h1 class=\"h3 mb-2 text-gray-800\">자유 게시판</h1>\n");
      out.write("          <br>\n");
      out.write("          \n");
      out.write("          <div class=\"card shadow mb-4\">\n");
      out.write("            <div class=\"card-header py-3\">\n");
      out.write("              <span class=\"m-0 font-weight-bold text-primary\">글 상세 보기</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("               \n");
      out.write("               \t  <div class=\"form-group\">\n");
      out.write("\t\t            <label>글번호</label> \n");
      out.write("\t\t            <input class=\"form-control\" id='bno' name='bno' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t          \n");
      out.write("\t\t          <div class=\"form-group\">\n");
      out.write("\t\t            <label>제목</label> \n");
      out.write("\t\t            <input class=\"form-control\" id='title' name='title' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t\n");
      out.write("\t\t          <div class=\"form-group\">\n");
      out.write("\t\t            <label>내용</label>\n");
      out.write("\t\t            <textarea class=\"form-control\" rows=\"3\" id='content' name='content'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t\n");
      out.write("\t\t          <div class=\"form-group\">\n");
      out.write("\t\t            <label>작성자</label> \n");
      out.write("\t\t            <input class=\"form-control\" id='writer' name='writer' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t          \n");
      out.write("\t\t          <div class=\"form-group\">\n");
      out.write("\t\t            <label>작성일자</label> \n");
      out.write("\t\t            <input class=\"form-control\" id='regDate' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.regDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t          \n");
      out.write("\t\t          <div class=\"form-group\">\n");
      out.write("\t\t            <label>수정일자</label> \n");
      out.write("\t\t            <input class=\"form-control\" id='updateDate' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.updateDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t          \n");
      out.write("\t\t          <div class=\"form-group\">\n");
      out.write("\t\t            <label>조회수</label> \n");
      out.write("\t\t            <input class=\"form-control\" id='readCount' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.readCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t          \n");
      out.write("\t\t          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t          <button id=\"tolist-button\" type=\"button\" class=\"btn btn-success\">목록</button>\n");
      out.write("\t\t       \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t<div class='rowx'>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-comments fa-fw\"></i>\n");
      out.write("\t\t\t\t\t\t<h2 class=\"d-inline\">Reply</h2>\n");
      out.write("\t\t\t\t\t\t<button id='addReplyBtn' class='btn btn-primary btn-xs pull-right float-right'>New Reply</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<div id=\"reply-list-container\" class=\"panel-body\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "reply-list.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<br><br><br><br><br>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container-fluid -->\n");
      out.write("      </div>\n");
      out.write("      <!-- End of Main Content -->\n");
      out.write("    </div>\n");
      out.write("    <!-- End of Content Wrapper -->\n");
      out.write("  </div>\n");
      out.write("  <!-- End of Page Wrapper -->\n");
      out.write("  \n");
      out.write("  \t<!-- Modal -->\n");
      out.write("\t<div class=\"modal fade\" id=\"reply-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"reply-modal-label\" aria-hidden=\"true\">\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"reply-modal-label\">댓글 쓰기</h5>\n");
      out.write("\t\t\t\t\t<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("            \t\t\t<span aria-hidden=\"true\">×</span>\n");
      out.write("          \t\t\t</button>\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t<form id=\"reply-form\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label>Reply</label>\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" name='reply' id='modal-reply' value=''>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label>Replyer</label>\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" name='replyer' id='modal-replyer' value=''>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name='bno' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name='rno'>\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name='action'> <!-- 댓글 or 대댓글 -->\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button id='modalModBtn' type=\"button\" class=\"btn btn-success\">Modify</button>\n");
      out.write("\t\t\t\t\t<button id='modalRemoveBtn' type=\"button\" class=\"btn btn-success\">Remove</button>\n");
      out.write("\t\t\t\t\t<button id='modalRegisterBtn' type=\"button\" class=\"btn btn-success\">Register</button>\n");
      out.write("\t\t\t\t\t<button id='modalCloseBtn' type=\"button\" class=\"btn btn-success\">Close</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.modal-content -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.modal-dialog -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- /.modal -->\n");
      out.write("\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript-->\r\n");
      out.write("  <script src=\"/spring-board-b/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/spring-board-b/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Core plugin JavaScript-->\r\n");
      out.write("  <script src=\"/spring-board-b/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for all pages-->\r\n");
      out.write("  <script src=\"/spring-board-b/resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"/spring-board-b/resources/js/sidebar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page level plugins -->\r\n");
      out.write("  <script src=\"/spring-board-b/resources/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page level custom scripts -->\r\n");
      out.write("  <script src=\"/spring-board-b/resources/js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("  <script src=\"/spring-board-b/resources/js/demo/chart-pie-demo.js\"></script>");
      out.write("\n");
      out.write("  \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\t\t\n");
      out.write("\t\t$('input, textarea').attr({'readonly': 'readonly'})\n");
      out.write("\t\t\n");
      out.write("\t\t$('#tolist-button').on('click', function(event) {\n");
      out.write("\t\t\tlocation.href = \"list.action?pageNo=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.pageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchType=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchKey=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchKey }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#delete-button').on('click', function(event) {\n");
      out.write("\n");
      out.write("\t\t\tvar yes = confirm(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("번 글을 삭제할까요?\");\n");
      out.write("\t\t\tif (!yes) {\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//location.href = 'delete.action?bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&pageNo=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.pageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t\t\tvar form =\n");
      out.write("\t\t\t\tmakeForm('delete.action', ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.pageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchKey }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\t\t\tform.submit();\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#edit-button').on('click', function(event) {\n");
      out.write("\t\t\t//location.href = \"update.action?bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\t\t\tvar form =\n");
      out.write("\t\t\t\tmakeForm('update.action', ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.pageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchKey }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\t\t\tform.submit();\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\tfunction makeForm(action, bno, pageNo, searchType, searchKey, method=\"get\") {\n");
      out.write("\t\t\tvar form = $('<form></form>');\n");
      out.write("\t\t\tform.attr({\n");
      out.write("\t\t\t\t'action': action,\n");
      out.write("\t\t\t\t'method': method\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\tform.append($('<input>').attr({\n");
      out.write("\t\t\t\t\"type\": \"hidden\",\n");
      out.write("\t\t\t\t\"name\": \"bno\",\n");
      out.write("\t\t\t\t\"value\" : bno })\n");
      out.write("\t\t\t);\n");
      out.write("\t\t\tform.append($('<input>').attr({\n");
      out.write("\t\t\t\t\"type\": \"hidden\",\n");
      out.write("\t\t\t\t\"name\": \"pageNo\",\n");
      out.write("\t\t\t\t\"value\" : pageNo })\n");
      out.write("\t\t\t);\n");
      out.write("\t\t\tform.append($('<input>').attr({\n");
      out.write("\t\t\t\t\"type\": \"hidden\",\n");
      out.write("\t\t\t\t\"name\": \"searchType\",\n");
      out.write("\t\t\t\t\"value\" : searchType })\n");
      out.write("\t\t\t);\n");
      out.write("\t\t\tform.append($('<input>').attr({\n");
      out.write("\t\t\t\t\"type\": \"hidden\",\n");
      out.write("\t\t\t\t\"name\": \"searchKey\",\n");
      out.write("\t\t\t\t\"value\" : searchKey })\n");
      out.write("\t\t\t);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tform.appendTo(\"body\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\treturn form;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t/////////////////////////////////////////////\n");
      out.write("\t// 댓글 관련 구현\n");
      out.write("\t\n");
      out.write("\t$(function() {\n");
      out.write("\n");
      out.write("\t\t$('#addReplyBtn').on('click', function(event) {\n");
      out.write("\n");
      out.write("\t\t\t$('#reply-form input[name!=bno]').attr({ \"readonly\": false }).val(\"\");\n");
      out.write("\n");
      out.write("\t\t\t$('#modalModBtn, #modalRemoveBtn').css({ \"display\": \"none\" });\n");
      out.write("\t\t\t$('#modalRegisterBtn').css({ \"display\": \"inline\" });\n");
      out.write("\n");
      out.write("\t\t\t$(\"#reply-form input[name=rno]\").val('0');\n");
      out.write("\t\t\t$('#reply-form input[name=action]').val('reply');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//show boot-strap modal\n");
      out.write("\t\t\t$('#reply-modal').modal('show');\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#modalCloseBtn').on('click', function(event) {\n");
      out.write("\t\t\t//hide boot-strap modal\n");
      out.write("\t\t\t$('#reply-modal').modal('hide');\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#modalRegisterBtn').on('click', function(event) {\n");
      out.write("\n");
      out.write("\t\t\tif ($('#modal-reply').val().length == 0) {\n");
      out.write("\t\t\t\talert(\"댓글 내용을 입력하세요\")\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// .serializeXXX : form의 모든 입력요소의 데이터를 전송 형식으로 변환\n");
      out.write("\t\t\t// var values = $('#reply-form').serialize();\n");
      out.write("\t\t\tvar values = $('#reply-form').serializeArray();\n");
      out.write("\t\t\t// console.log(values); return;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\"url\": \"/spring-board-b/reply/write\",\n");
      out.write("\t\t\t\t\"method\": \"post\",\n");
      out.write("\t\t\t\t\"data\": values,\n");
      out.write("\t\t\t\t\"success\": function(data, status, xhr) {\n");
      out.write("\t\t\t\t\t$('#reply-modal').modal('hide');\n");
      out.write("\n");
      out.write("\t\t\t\t\t//1. 비동기 목록 요청 1\n");
      out.write("\t\t\t\t\t//   댓글 목록 조회 (JSON)\n");
      out.write("\t\t\t\t\t//   조회된 데이터를 사용해서 javascript로 화면 생성 (HTML)\n");
      out.write("\t\t\t\t\t//2. 비동기 목록 요청 2\n");
      out.write("\t\t\t\t\t//   댓글 목록을 사용해서 만들어진 HTML을 수신해서 화면에 적용\n");
      out.write("\t\t\t\t\t$('#reply-list-container').load(\"/spring-board-b/reply/list-by/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t\"error\": function(xhr, status, err) {\n");
      out.write("\t\t\t\t\talert('댓글 쓰기 실패');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t// 페이지가 로딩되면 즉시 댓글 목록을 비동기 방식으로 요청해서 화면에 적용\n");
      out.write("\t\t// $('#reply-list-container').load(\"/spring-board-b/reply/list-by/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\n");
      out.write("\t\t// $('.reply-delete').on('click', function(event) {\n");
      out.write("\t\t$('#reply-list-container').on('click', '.reply-delete', function(event) { // 사라지지 않는 상위객체에 이벤트 전달을 대행시킴 (event delegation)\n");
      out.write("\t\t\tvar rno = $(this).attr('data-rno'); // this : 이벤트 발생 객체\n");
      out.write("\n");
      out.write("\t\t\tvar yes = confirm(rno + \"번 댓글을 삭제할까요?\");\n");
      out.write("\t\t\tif (!yes) return;\n");
      out.write("\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\"url\": \"/spring-board-b/reply/delete/\" + rno,\n");
      out.write("\t\t\t\t\"method\": \"delete\",\n");
      out.write("\t\t\t\t//\"data\": { \"rno\" : rno },\n");
      out.write("\t\t\t\t\"success\": function(data, status, xhr) {\n");
      out.write("\t\t\t\t\t//댓글 목록 갱신\n");
      out.write("\t\t\t\t\t$('#reply-list-container').load(\"/spring-board-b/reply/list-by/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t\"error\": function(xhr, status, err) {\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#reply-list-container').on('click', '.reply-update', function(event) {\n");
      out.write("\n");
      out.write("\t\t\tvar rno = $(this).attr(\"data-rno\"); // update button에 설정된 rno\n");
      out.write("\t\t\tvar li = $(\"li[data-rno=\" + rno + \"]\"); // rno와 일치하는 li\n");
      out.write("\t\t\tvar p = li.find(\"p\"); // li에 포함된 p\n");
      out.write("\t\t\tvar strong = li.find(\"strong\"); // li에 포함된 strong\n");
      out.write("\n");
      out.write("\t\t\t$('#reply-form input[name!=bno]').attr({ \"readonly\": false }).val(\"\");\n");
      out.write("\t\t\t// $('#modal-reply').val(p.text().replace(/(^\\s*)|(\\s*$)/g, \"\"));\n");
      out.write("\t\t\t$('#modal-reply').val($.trim(p.text()));\n");
      out.write("\t\t\t$('#modal-replyer').attr({ \"readonly\": true }).val(strong.text());\n");
      out.write("\n");
      out.write("\t\t\t$('#modalRegisterBtn, #modalRemoveBtn').css({ \"display\": \"none\" });\n");
      out.write("\t\t\t$('#modalModBtn').css({ \"display\": \"inline\" });\n");
      out.write("\n");
      out.write("\t\t\t$(\"#reply-form input[name=rno]\").val(rno);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//show boot-strap modal\n");
      out.write("\t\t\t$('#reply-modal').modal('show');\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$(\"#modalModBtn\").on('click', function(event) {\n");
      out.write("\n");
      out.write("\t\t\tvar data = {\n");
      out.write("\t\t\t\t\"rno\": $(\"#reply-form input[name=rno]\").val(),\n");
      out.write("\t\t\t\t\"reply\": $(\"#reply-form input[name=reply]\").val()\n");
      out.write("\t\t\t};\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\"url\": \"/spring-board-b/reply/update\",\n");
      out.write("\t\t\t\t\"method\": \"PUT\",\n");
      out.write("\t\t\t\t\"data\": JSON.stringify(data), // JSON Object -> JSON String\n");
      out.write("\t\t\t\t\"contentType\": \"application/json\", // PUT method 처리를 위해 설정\n");
      out.write("\t\t\t\t\"success\": function(result, status, xhr) {\n");
      out.write("\t\t\t\t\t$(\"#reply-modal\").modal('hide');\n");
      out.write("\t\t\t\t\t$('#reply-list-container').load(\"/spring-board-b/reply/list-by/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ board.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t\"error\": function(xhr, status, err) {\n");
      out.write("\t\t\t\t\talert('댓글 수정 실패');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#reply-list-container').on('click', '.reply-reply', function(event) {\n");
      out.write("\n");
      out.write("\t\t\tvar rno = $(this).attr(\"data-rno\");\n");
      out.write("\n");
      out.write("\t\t\t$('#reply-form input[name!=bno]').attr({ \"readonly\": false }).val(\"\");\n");
      out.write("\n");
      out.write("\t\t\t$('#modalRegisterBtn').css({ \"display\": \"inline\" });\n");
      out.write("\t\t\t$('#modalModBtn, #modalRemoveBtn').css({ \"display\": \"none\" });\n");
      out.write("\n");
      out.write("\t\t\t$(\"#reply-form input[name=rno]\").val(rno);\n");
      out.write("\t\t\t$('#reply-form input[name=action]').val('re-reply');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//show boot-strap modal\n");
      out.write("\t\t\t$('#reply-modal').modal('show');\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/detail.jsp(89,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginuser.email == board.writer }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t          <button id=\"edit-button\" type=\"button\" class=\"btn btn-success\">수정</button>\n");
          out.write("\t\t          <button id=\"delete-button\" type=\"button\" class=\"btn btn-success\">삭제</button>\n");
          out.write("\t\t          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
